DROP TABLE IF EXISTS `#__sabullvial_cliente`;

CREATE TABLE `#__sabullvial_cliente` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`id_condicionventa` INT(11)  NOT NULL,
    `razon_social` VARCHAR(255) NULL,
    `actividad_comercial` VARCHAR(255) NULL,
    `cuit` VARCHAR(20) NULL,
    `pagina_web` VARCHAR(255) NULL,
    `grupo_empresario` VARCHAR(255) NULL,
    `aclaracion` VARCHAR(255) NULL,
    `direccion_comercial_calle` VARCHAR(255) NULL,
    `direccion_comercial_calle_numero` VARCHAR(10),
    `direccion_comercial_ciudad` VARCHAR(255) NULL,
    `direccion_comercial_codigo_postal` VARCHAR(10),
    `direccion_comercial_provincia` VARCHAR(255) NULL,
    `direccion_comercial_telefono` VARCHAR(20),
    `direccion_comercial_celular` VARCHAR(20),
    `direccion_entrega_calle` VARCHAR(255) NULL,
    `direccion_entrega_calle_numero` VARCHAR(10),
    `direccion_entrega_ciudad` VARCHAR(255) NULL,
    `direccion_entrega_codigo_postal` VARCHAR(10),
    `direccion_entrega_provincia` VARCHAR(255) NULL,
    `encargado_compras_nombre` VARCHAR(255) NULL,
    `encargado_compras_telefono` VARCHAR(20),
    `encargado_compras_celular` VARCHAR(20),
    `encargado_compras_interno` VARCHAR(10),
    `encargado_compras_email` VARCHAR(255) NULL,
    `encargado_pagos_nombre` VARCHAR(255) NULL,
    `encargado_pagos_telefono` VARCHAR(20),
    `encargado_pagos_celular` VARCHAR(20),
    `encargado_pagos_interno` VARCHAR(10),
    `encargado_pagos_email` VARCHAR(255) NULL,
    `referencia_comercial_1_empresa` VARCHAR(255) NULL,
    `referencia_comercial_1_contacto` VARCHAR(255) NULL,
    `referencia_comercial_1_telefono` VARCHAR(20),
    `referencia_comercial_2_empresa` VARCHAR(255) NULL,
    `referencia_comercial_2_contacto` VARCHAR(255) NULL,
    `referencia_comercial_2_telefono` VARCHAR(20),
    `referencia_comercial_3_empresa` VARCHAR(255) NULL,
    `referencia_comercial_3_contacto` VARCHAR(255) NULL,
    `referencia_comercial_3_telefono` VARCHAR(20),
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` int unsigned NOT NULL DEFAULT 0,
	`created_by_alias` varchar(255) NOT NULL DEFAULT '',
	`modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` int unsigned NOT NULL DEFAULT 0,
	`published` tinyint(4) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`)
) ENGINE=MyISAM	AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;