-- Optimizaciones para las tablas SIT
ALTER TABLE `SIT_CLIENTES` CHANGE `COD_CLIENT` `COD_CLIENT` VARCHAR(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `SIT_CLIENTES_DIRECCION_ENTREGA` CHANGE `COD_CLIENT` `COD_CLIENT` VARCHAR(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;