-- ALTER TABLE `SIT_ARTICULOS` CHANGE `COD_ARTICU` `COD_ARTICU` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 
-- ALTER TABLE `SIT_ARTICULOS_PRECIOS` CHANGE `COD_ARTICU` `COD_ARTICU` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 
-- ALTER TABLE `SIT_CLIENTES` CHANGE `COD_VENDED` `COD_VENDED` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL; 

-- ALTER TABLE `SIT_ARTICULOS` ADD INDEX `CLASIF_1_idx` (`CLASIF_1`); 
ALTER TABLE `SIT_CLIENTES` ADD INDEX `COD_VENDED_idx` (`COD_VENDED`);
ALTER TABLE `SIT_CLIENTES` ADD INDEX `INHABILITADO_idx` (`INHABILITADO`); 

ALTER TABLE `#__sabullvial_cotizacion` ADD INDEX `tango_enviar_idx` (`tango_enviar`); 
ALTER TABLE `#__sabullvial_cotizacion` ADD INDEX `created_idx` (`created`);
