/*ALTER TABLE `SIT_PEDIDOS_REMITOS` ADD INDEX `n_remito_idx` (`N_REMITO`);
ALTER TABLE `SIT_PEDIDOS_REMITOS` ADD INDEX `cod_client_idx` (`COD_CLIENT`);
ALTER TABLE `SIT_PEDIDOS_REMITOS` ADD INDEX `cod_vended_idx` (`COD_VENDED`);
ALTER TABLE `SIT_PEDIDOS_REMITOS` ADD INDEX `id_pedido_web_idx` (`ID_PEDIDO_WEB`);
ALTER TABLE `SIT_PEDIDOS_FACTURAS` ADD INDEX `id_pedido_web_idx` (`ID_PEDIDO_WEB`);
ALTER TABLE `SIT_PEDIDOS_FACTURAS` ADD INDEX `ncomp_fac_idx` (`NCOMP_FAC`);
ALTER TABLE `SIT_ARTICULOS_PRECIOS` ADD INDEX `cod_articu_idx` (`COD_ARTICU`);
ALTER TABLE `SIT_ARTICULOS_PRECIOS` ADD INDEX `cod_lista_idx` (`COD_LISTA`);*/